### ISSUE TITLE
dtcw.ps1 fails to run with downloaded Adoptium jdk-17.0.8.1+1

### ISSUE THREAD

**Issue by kvt11** [docToolchain/docToolchain#1252]
**Describe the bug**

I found 2 minor issues when doing a fresh installation on Windows 11:

1. Current Adoptium Java jdk-17.0.8.1+1 conflicts with reference version in dtcw.ps1

2. Invoke-Expression uses Unix I/O redirection

**To Reproduce**
1. .\dtcw.ps1 local install doctoolchain
2. .\dtcw.ps1 install java
3.  .\dtcw.ps1 tasks -group doctoolchain
```
dtcw 0.52 - ##DTCW_GIT_HASH##
docToolchain 3.0.2
OS/arch: pwsh windows x64
Available docToolchain environments: local
Environments with docToolchain [3.0.2]: local
Using environment: local
local java JDK-17 found
Invoke-Expression : Die Benennung "C:\Users\thadden/.doctoolchain/jdk/jdk-17.0.7+7/bin/java" wurde nicht als Name
eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren Programms erkannt. Überprüfen Sie die
Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.
In C:\devel\UCMDB\workspace\UCMDB_SHG\tasks\Training\training-docs\dtcw.ps1:412 Zeichen:22
+ ... version = ((Invoke-Expression -Command "$JAVA_CMD -version 2>&1" | Se ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\thadde....0.7+7/bin/java:String) [Invoke-Expression], CommandN
   otFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.InvokeExpressionCommand


```
6. workaround by fixing hardcoded path to java.exe

7. run again

```
.\dtcw.ps1 tasks -group doctoolchain
dtcw 0.52 - ##DTCW_GIT_HASH##
docToolchain 3.0.2
OS/arch: pwsh windows x64
Available docToolchain environments: local
Environments with docToolchain [3.0.2]: local
Using environment: local
local java JDK-17 found
C:\Users\thadden/.doctoolchain/jdk/jdk-17.0.8.1+1/bin/java : openjdk version "17.0.8.1" 2023-08-24
In Zeile:1 Zeichen:1
+ C:\Users\thadden/.doctoolchain/jdk/jdk-17.0.8.1+1/bin/java -version 2 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (openjdk version "17.0.8.1" 2023-08-24:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

```

**Expected behavior**
simply run and kick off gradle

**Screenshots**
n/a

**Configuration**

 - dtcw.ps1 3.0.2
 - OS: Windows 10

```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.3031
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3031
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Additional context**

Reason for Issue 1
Line 403 has a hardcoded version 
$javaHome = "$DTC_JAVA_HOME/jdk-17.0.7+7"

This can be fixed quickly by
$javaHome = "$DTC_JAVA_HOME/jdk-17.0.8.1+1"

Reason for Issue 2
Line 412 uses unix like handling of stderr
... Invoke-Expression -Command "$JAVA_CMD -version 2>&1" ...

This can be fixed quickly by removing the intended redirection of stderr to stdout
... Invoke-Expression -Command "$JAVA_CMD -version" ...

**Comment by A-n-d-y-K** [comment]
Hello @kvt11 ,
thanks for sharing your workarounds in file dtcw.ps1, sadly it does not work on my side. May you could help me out.

Thanks in advance

OS = windows 10

line 403:
- old: `$javaHome = "DTC_JAVA_HOME/jdk-17.0.7+7"`
- new: `$javaHome = "$DTC_JAVA_HOME/jdk-17.0.8.1+1"`

line 412:
- old: `$javaversion = ((Invoke-Expression -Command "$JAVA_CMD -version 2>&1" | Select-String -Pattern 'version').Line | Select-Object -First 1 ).Split('"')[1].Split(".")[0]`
- new: `    $javaversion = ((Invoke-Expression -Command "$JAVA_CMD -version" | Select-String -Pattern 'version').Line | Select-Object -First 1 ).Split('"')[1].Split(".")[0]`

This is PowerShell output:
```
PS G:\Projects\docToolchain> .\dtcw.ps1 local install doctoolchain
dtcw 0.52 - ##DTCW_GIT_HASH##
docToolchain 3.0.2                                                                                                                     OS/arch: pwsh windows x64                                                                                                              Available docToolchain environments: local                                                                                             Environments with docToolchain [3.0.2]: local                                                                                          Using environment: local                                                                                                               Installed docToolchain successfully in 'C:\Users\kaluzaa/.doctoolchain/docToolchain-3.0.2'.

Use './dtcw.ps1 tasks --group doctoolchain' to see docToolchain related tasks.
java version "1.8.0_381"
Java(TM) SE Runtime Environment (build 1.8.0_381-b31)
Java HotSpot(TM) 64-Bit Server VM (build 25.381-b31, mixed mode)
Es ist nicht möglich, eine Methode für einen Ausdruck aufzurufen, der den NULL hat.
In G:\Projects\docToolchain\dtcw.ps1:412 Zeichen:5
+     $javaversion = ((Invoke-Expression -Command "$JAVA_CMD -version"  ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvokeMethodOnNull

PS G:\Projects\docToolchain>
```

**Comment by kvt11** [comment]
Hello @A-n-d-y-K ,

had to get the script working somehow and I must admit that at the end of this evening I ended up with just hardcoding $javaversion 

.line 412 old:
----
$javaversion = ((Invoke-Expression -Command "$JAVA_CMD -version 2>&1" | Select-String -Pattern 'version').Line | Select-Object -First 1 ).Split('"')[1].Split(".")[0]
----

.line 412 new:
----
$javaversion = '17'
----

I have also changed quoting of options in my local copy later

.line 31 old
----
$DTC_OPTS = "$env:DTC_OPTS -PmainConfigFile='$DTC_CONFIG_FILE' --warning-mode=none --no-daemon -Dfile.encoding=UTF-8 "
----
.line 31 new
----
$DTC_OPTS = "$env:DTC_OPTS -PmainConfigFile='$DTC_CONFIG_FILE' ""--warning-mode=none"" ""--no-daemon"" ""-Dfile.encoding=UTF-8"" "
----

I hope this helps for your copy.

Best regards,
kvt11

**Comment by A-n-d-y-K** [comment]
Hello @kvt11 ,
thanks much for your answer and suggestion. I applied only the 2x changes (line 31 and line 412), additionally I installed java 17.0.9 on my machine. Sadly I run into an SSL security error. 
Kindly ask for your expertise again.

```
Windows PowerShell
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
                                                                                                                                                                                                                                            Lernen Sie das neue plattformübergreifende PowerShell kennen – https://aka.ms/pscore6                                                                                                                                                                                                                                                                                                                                                                                                   PS C:\Users\kaluzaa> g:                                                                                                                                                                                                                     PS G:\> cd .\Projects\docToolchain\                                                                                                                                                                                                         PS G:\Projects\docToolchain> **.\dtcw.ps1 local install doctoolchain**
dtcw 0.52 - ##DTCW_GIT_HASH##
docToolchain 3.0.2
OS/arch: pwsh windows x64
Available docToolchain environments: local
Environments with docToolchain [3.0.2]:
Using environment: local
Installed docToolchain successfully in 'C:\Users\kaluzaa/.doctoolchain/docToolchain-3.0.2'.

Java Version 17
Using Java 17 [java]
PS G:\Projects\docToolchain> **.\dtcw.ps1 tasks -group doctoolchain**
dtcw 0.52 - ##DTCW_GIT_HASH##
docToolchain 3.0.2
OS/arch: pwsh windows x64
Available docToolchain environments: local
Environments with docToolchain [3.0.2]: local
Using environment: local
Java Version 17
Using Java 17 [java]
Downloading https://services.gradle.org/distributions/gradle-8.1.1-bin.zip

Exception in thread "main" javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:378)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:316)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
        at java.base/sun.security.ssl.CertificateStatus$CertificateStatusConsumer.consume(CertificateStatus.java:293)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:589)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:87)
        at org.gradle.wrapper.Download.download(Download.java:67)
        at org.gradle.wrapper.Install$1.call(Install.java:68)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
        at java.base/sun.security.validator.Validator.validate(Validator.java:264)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
        ... 23 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148)
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129)
        at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
        ... 28 more
PS G:\Projects\docToolchain> java -version
java version "17.0.9" 2023-10-17 LTS
Java(TM) SE Runtime Environment (build 17.0.9+11-LTS-201)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.9+11-LTS-201, mixed mode, sharing)
PS G:\Projects\docToolchain>
```

**Comment by git-developer** [comment]
Looks like your JVM does not trust `https://services.gradle.org`. I don't know why this happens, but you could try to configure the JRE to use the Windows certificates by setting the environment variable

`JAVA_TOOL_OPTIONS="-Djavax.net.ssl.trustStoreType=WINDOWS-ROOT"`
