### ISSUE TITLE
generatePDF throws exception when using custom-theme.yml (font not found in GEM_FONTS_DIR)

### ISSUE THREAD

**Issue by Barney-42** [docToolchain/docToolchain#1460]
**Describe the bug**
PDF generation with custom-theme.yml throws an exception, because file mplus1mn-regular-ascii-conums.ttf not found in GEM_FONTS_DIR.

**To Reproduce**
1. Install docToolchain like described in [https://doctoolchain.org/docToolchain/v2.0.x/010_manual/20_install.htm](https://doctoolchain.org/docToolchain/v2.0.x/010_manual/20_install.htm)
```
- curl -Lo dtcw.bat doctoolchain.org/dtcw.bat
- dtcw.bat install doctoolchain
- dtcw.bat install java
- dtcw.bat tasks --group=doctoolchain
```
3. download Arc42 template (`dtcw.bat downloadTemplate`)
4. Uncomment line `pdfThemeDir = './src/docs/pdfTheme` in `docToolchainConfig.groovy`
5. Copy pdfTheme to project (`dtcw copyTheme`)
6. Navigate to `src/docs/arc42/arc42.adoc` then add the following to the top of the document (like described in [https://doctoolchain.org/docToolchain/v2.0.x/020_tutorial/030_generateHTML.html#_pdf_style](https://doctoolchain.org/docToolchain/v2.0.x/020_tutorial/030_generateHTML.html#_pdf_style):
```
pdf-themesdir: ../pdfTheme
:pdf-theme: custom
``` 

8. Try to generate PDF (`dtcw generatePDF`)
9. generatePDF throws the following exception

```
Task :generatePDF
Converting C:\Users\MaxMustermann\Documents\MyProject\src\docs\arc42\arc42.adoc
Nov. 15, 2024 5:01:07 PM uri:classloader:/gems/asciidoctor-pdf-2.3.4/lib/asciidoctor/pdf/theme_loader.rb load
WARNUNG: the outline-list theme category is deprecated; use the list category instead
Nov. 15, 2024 5:01:07 PM org.asciidoctor.jruby.internal.JRubyAsciidoctor convertFile
SCHWERWIEGEND: (ENOENT) No such file or directory - mplus1mn-regular-ascii-conums.ttf not found in GEM_FONTS_DIR
Exception in thread "main" org.asciidoctor.gradle.remote.AsciidoctorRemoteExecutionException: Error running Asciidoctor whilst attempting to process C:\Users\MaxMustermann\Documents\MyProject\src\docs\arc42\arc42.adoc using backend pdf
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec$_convertFiles_closure4.doCall(AsciidoctorJavaExec.groovy:91)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:428)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2357)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2342)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2395)
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec.convertFiles(AsciidoctorJavaExec.groovy:82)
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec.access$1(AsciidoctorJavaExec.groovy)
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec$_run_closure3.doCall(AsciidoctorJavaExec.groovy:73)
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec$_run_closure3.call(AsciidoctorJavaExec.groovy)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2357)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2342)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2383)
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec.run(AsciidoctorJavaExec.groovy:68)
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec.main(AsciidoctorJavaExec.groovy:49)
Caused by: org.asciidoctor.jruby.internal.AsciidoctorCoreException: org.jruby.exceptions.SystemCallError: (ENOENT) No such file or directory - mplus1mn-regular-ascii-conums.ttf not found in GEM_FONTS_DIR
        at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:402)
        at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:368)
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec$_convertFiles_closure4.doCall(AsciidoctorJavaExec.groovy:87)
        ... 22 more
Caused by: org.jruby.exceptions.SystemCallError: (ENOENT) No such file or directory - mplus1mn-regular-ascii-conums.ttf not found in GEM_FONTS_DIR
        at RUBY.register_fonts(uri:classloader:/gems/asciidoctor-pdf-2.3.4/lib/asciidoctor/pdf/converter.rb:4039)
        at org.jruby.RubyHash.each(org/jruby/RubyHash.java:1519)
        at RUBY.register_fonts(uri:classloader:/gems/asciidoctor-pdf-2.3.4/lib/asciidoctor/pdf/converter.rb:4034)
        at org.jruby.RubyKernel.tap(org/jruby/RubyKernel.java:1940)
        at RUBY.register_fonts(uri:classloader:/gems/asciidoctor-pdf-2.3.4/lib/asciidoctor/pdf/converter.rb:4033)
        at org.jruby.RubyHash.each(org/jruby/RubyHash.java:1519)
        at RUBY.register_fonts(uri:classloader:/gems/asciidoctor-pdf-2.3.4/lib/asciidoctor/pdf/converter.rb:4032)
        at RUBY.init_pdf(uri:classloader:/gems/asciidoctor-pdf-2.3.4/lib/asciidoctor/pdf/converter.rb:392)
        at RUBY.convert_document(uri:classloader:/gems/asciidoctor-pdf-2.3.4/lib/asciidoctor/pdf/converter.rb:163)
        at RUBY.convert(uri:classloader:/gems/asciidoctor-pdf-2.3.4/lib/asciidoctor/pdf/converter.rb:152)
        at RUBY.convert(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/document.rb:956)
        at RUBY.convert(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/convert.rb:118)
        at RUBY.convert_file(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/convert.rb:190)
        at org.jruby.RubyIO.open(org/jruby/RubyIO.java:1148)
        at RUBY.convert_file(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/convert.rb:190)

> Task :generatePDF FAILED
```
**Expected behavior**
No exception

**Configuration**
 - docToolchain version 3.4.1
 - OS: Windows 11

**Additional context**
Without the use of custom-theme.yml, the PDF generations work perfectly. The problem could be reproduced on 2 different PCs. Reinstalling doctoolchain does not solve the problem. Also no difference whether docToolchain is installed via PowershellWindows or cmd.exe.

**Comment by PacoVK** [comment]
Hey @Barney-42  thanks for reporting this. I provided a fix in #1470  :)
