### ISSUE TITLE
Docs: Feedback for 'Self-Contained docToolchain'

### ISSUE THREAD

**Issue by SidekickJohn** [docToolchain/docToolchain#890]
I tried following the documentation on how to get a self-contained version of doctoolchain (without docker). Sadly this did not work out as expected.

## Environment
- Windows 10
- CMD
- no previous installation of Gradle present (Maven user ;-) )
- unrestricted network/internet access

## Steps executed
- http://doctoolchain.org/docToolchain/v2.0.x/020_tutorial/010_Install.html --> "Get Wrapper" --> Worked
- `dtcw.bat tasks --group=doctoolchain` --> to test install --> Worked (Build Successful) --> but no task for `getJava` available
- `dtcw.bat local getJava` --> **BUILD FAILURE**

## Problem encountered
```commandline
FAILURE: Build failed with an exception.

* What went wrong:
Task 'getJava' not found in root project 'docToolchain'.
```

## Question/Issue
Just following the docs I did not find a solution for this issue. 

---
#page: https://github.com/doctoolchain/doctoolchain/edit/ng/src/docs/020_tutorial/120_self-contained-dtc.adoc
#branch: ng

**Comment by rdmueller** [comment]
thanx for the feedback. let me try to reproduce it.
btw: on Windows 10, I would suggest to use powershell.

**Comment by rdmueller** [comment]
hm. what I did is

```
curl -Lo dtcw.bat doctoolchain.github.io/dtcw.bat
dtcw getJava
```

and I got

```
fatal: not a git repository (or any of the parent directories): .git
local java JDK-11 found
dtcw - docToolchain wrapper V0.24 (PS)
docker available
dtcw folder exist: 'C:\Users\ralfd\.doctoolchain'
this script assumes that you have a 64 bit Windows installation
it now tries to install Java for you
downloadting JDK temurin11 from adoptiom to C:\Users\ralfd\.doctoolchain/jdk.zip
```

can you copy and paste the output of your `dtcw getJava`? Most important is the line with the version of the wrapper `dtcw - docToolchain wrapper V0.24 (PS)`.

**Comment by SidekickJohn** [comment]
I noticed you used:
`dtcw getJava` 

Instead of:
`dtcw local getJava` 

I'll try this and come back asap.

**Comment by rdmueller** [comment]
ah, good point. It could be that there is room for improvement. `dtcw local getJava` should also work. Have to check that

**Comment by SidekickJohn** [comment]
Ok, using `dtcw getJava` (without local) triggered the download for the Java jdk.zip.   
I don't have any Docker setup running, so this worked quite well.  
Running `dtcw local tasks` afterwards also works like a charm.  
I finished it up running the "get dependencies" part which also worked.  

All packed (zipped) up and ready to go --> Will try this "package" tomorrow in the restricted environment and provide further feedback if that worked out.

**Comment by rdmueller** [comment]
btw: you only need the parameter `local` when you have docker installed and docToolchain is not installed yet.

If you omit the parameter, `dtcw` will 

- first check if there is a local version installed
- if not it checks if docker is installed
- if not will prompt you to install doctoolchain locally

so, with a local install available, it will use it, no matter what parameter is given

**Comment by SidekickJohn** [comment]
Thanks for clarifying. 

Ok, so I got to test the .zip in the restricted environment. Unfortunately it did not work.  
Seems like `gradle` still wants to download it's distribution first (see error-output below).

### Steps to reproduce

1. Copy .zip to environment
2. Unzip it and place content in `$HOME/.doctoolchain`
3. Get `dtcw.bat` and use simple function call to test installation: `dtcw tasks --group=doctoolchain`

### Error-Output
The commandline output is the following. I replaced my actual username with "username".
```
D:\Users\username\Desktop\docToolChain>dtcw tasks --group=doctoolchain
fatal: not a git repository (or any of the parent directories): .git
local java JDK-11 found
dtcw - docToolchain wrapper V0.24 (PS)
dtcw folder exist: 'D:\Users\username\.doctoolchain'
Command to invoke: '&'D:\Users\username\.doctoolchain\docToolchain-2.0.5\bin\doctoolchain.bat' . tasks --group=doctoolchain  -PmainConfigFile='docToolchainConfig.groovy' --warning-mode=none --no-daemon '--gradle-user-home=D:\Users\username\.doctoolchain\.gradle' '-Dorg.gradle.java.home=D:\Users\username\.doctoolchain\jdk-11.0.15+10' '
Downloading https://services.gradle.org/distributions/gradle-6.9.2-bin.zip

Exception in thread "main" java.net.UnknownHostException: services.gradle.org
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:229)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:300)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:373)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:87)
        at org.gradle.wrapper.Download.download(Download.java:67)
        at org.gradle.wrapper.Install$1.call(Install.java:68)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
```

**Comment by SidekickJohn** [comment]
Update: I got a little workaround for my previous mentioned problem.

I followed the hint on this page (https://chengl.com/gradle-offline-build/):

> Simply modify distributionUrl in gradle-wrapper.properties to a local path, e.g.


So I went to the folder: `.doctoolchain/docToolchain-2.0.5/gradle/wrapper` and opened the `gradle-wrapper.properties`. I changed the `distributionUrl` to a local URL:
```
# Other properties omitted
distributionUrl=gradle-6.9.2-bin.zip
```
Then I downloaded the binary from: https://services.gradle.org/distributions/ and placed it in the same folder mentioned above  (.../wrapper).

> From now on, you can build using Gradle without Gradle installed

Gradle now uses the local binary instead of downloading it and this works fine.

**Comment by rdmueller** [comment]
thanx for the update! Yes, the distribution is missing from the tutorial:

https://doctoolchain.org/docToolchain/v2.0.x/020_tutorial/120_self-contained-dtc.html

would you mind to update the tutorial with your additional knowledge?

https://github.com/doctoolchain/doctoolchain/edit/ng/src/docs/020_tutorial/120_self-contained-dtc.adoc

**Comment by SidekickJohn** [comment]
Yes I'll try to find some time to update the docs and provide a pull request... Well I'll read the contribution guideline first and propose the doc changes afterwards in the preferred way.

**Comment by SidekickJohn** [comment]
@rdmueller it took me only 3 months but I finally found some time to file a PR for this. sorry for taking so long. hope I did well and the PR meets your expectations. otherwise just let me know and I'll try to get back to this a little faster this time ;-)

all the best for the upcoming holidy-season, stay well and have a good time.

regards Jan
