### ISSUE TITLE
InvalidUserDataException: Cannot convert URL '[...]\.doctoolchain\.gradle' to a file

### ISSUE THREAD

**Issue by erikhofer** [docToolchain/docToolchain#914]
**Describe the bug**
When I install the wrapper on Windows and try to execute any task, I get the following error message:

```
dtcw - docToolchain wrapper V0.24 (PS)
docker available
docker.exe
Command to invoke: 'docker.exe run --name doctoolchain2.1.0 -e DTC_HEADLESS=1 -e DTC_SITETHEME -p 8042:8042 --rm -it --entrypoint /bin/bash -v 'C:\Projekte\docToolchain-test:/project' 'doctoolchain/doctoolchain:v2.1.0' -c "doctoolchain . tasks --group=doctoolchain  -PmainConfigFile='docToolchainConfig.groovy' --warning-mode=none --no-daemon '--gradle-user-home=C:\Users\Erik\.doctoolchain\.gradle' && exit"'

FAILURE: Build failed with an exception.

* What went wrong:
Cannot convert URL 'C:\Users\Erik\.doctoolchain\.gradle' to a file.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.InvalidUserDataException: Cannot convert URL 'C:\Users\Erik\.doctoolchain\.gradle' to a file.
        at org.gradle.api.internal.file.BasicFileResolver.transform(BasicFileResolver.java:58)
        at org.gradle.api.internal.file.BasicFileResolver.transform(BasicFileResolver.java:34)
        at org.gradle.initialization.BuildLayoutParametersBuildOptions$GradleUserHomeOption.applyTo(BuildLayoutParametersBuildOptions.java:56)
        at org.gradle.initialization.BuildLayoutParametersBuildOptions$GradleUserHomeOption.applyTo(BuildLayoutParametersBuildOptions.java:48)
        at org.gradle.internal.buildoption.StringBuildOption.applyFromCommandLine(StringBuildOption.java:60)
        at org.gradle.internal.buildoption.BuildOptionSet$1.convert(BuildOptionSet.java:42)
        at org.gradle.initialization.LayoutCommandLineConverter.convert(LayoutCommandLineConverter.java:32)
        at org.gradle.initialization.LayoutCommandLineConverter.convert(LayoutCommandLineConverter.java:27)
        at org.gradle.launcher.cli.converter.BuildLayoutConverter.convert(BuildLayoutConverter.java:58)
        at org.gradle.launcher.cli.converter.BuildLayoutConverter.convert(BuildLayoutConverter.java:46)
        at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:220)
        at org.gradle.launcher.Main.doAction(Main.java:35)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:50)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:31)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:35)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)


* Get more help at https://help.gradle.org
```

**To Reproduce**
1. `Invoke-WebRequest doctoolchain.github.io/dtcw.ps1 -Outfile dtcw.ps1`
2. `./dtcw.ps1 tasks --group=doctoolchain`
3. See error

**Configuration**
 - docToolchain 2.0.5 and 2.1.0 (tried both)
 - Windows 10

```
λ java -version
java version "18.0.1.1" 2022-04-22
Java(TM) SE Runtime Environment (build 18.0.1.1+2-6)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)
```

**Comment by jmini** [comment]
This line seems to be wrong:

https://github.com/docToolchain/docToolchain/blob/a8a3ca4ef7544922a7fd115739242a0dfbc4bc6f/dtcw.ps1#L17

It seems that gradle is not able to parse the [cli option](https://docs.gradle.org/current/userguide/command_line_interface.html#sec:environment_options) `--gradle-user-home`

I would try to modify the script `dtcw.ps1` to pass a value that is a URI (starting with `file://C/User/Erik...`)
Now that I am thinking about it, I am don't understand how this is supposed to work, since you are inside a container and you probably don't have access to `C:\Users\Erik\.doctoolchain\.gradle`

The docker run command in the dtcw script does not set the `--gradle-user-home`

https://github.com/docToolchain/docToolchain/blob/a8a3ca4ef7544922a7fd115739242a0dfbc4bc6f/dtcw#L333

**Comment by rdmueller** [comment]
hm. When did I break this?
let me fix it tomorrow morning.

**Comment by rdmueller** [comment]
Please try again. I have fixed this problem within the doctoolchain wrapper (dtcw).

The problem only occured when dtcw was used with docker.

New version is tested on both, bash and powershell,
- local install
- docker
- CI/CD

**Comment by erikhofer** [comment]
Works on my end as well. Thanks a lot for the quick solution! :)
