### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: /exception(par/: Unterminated group

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#928]
When you do a local search, you often get the followin error in the javascript console

```
Uncaught SyntaxError: Invalid regular expression: /exception(par/: Unterminated group
    at new RegExp (<anonymous>)
    at lunrdosearch.js:30:38
    at Array.forEach (<anonymous>)
    at lunrdosearch.js:24:49
    at Array.forEach (<anonymous>)
    at dosearch (lunrdosearch.js:18:17)
    at HTMLInputElement.onkeyup (search.html?q=excel:221:113)
```

**Comment by rdmueller** [comment]
so, the problem was, that for highlighting the search result, a case insensitive search was needed. So, string.replace was used with a regexp (the search term). Problem was, when this regexp contained special characters.
